## Numpy

Numpy is a Linear Algebra Library for Python. Most of the PyData Ecosystems use Numpy as base.

Numpy arrays essentially com in two types: Vectors and Matrices. Vectors are stricly 1d arrays and marices are 2d arrays.

In [1]:
import numpy as np

In [4]:
#Create array Vector
my_list = [1,2,3]
array = np.array(my_list)
array

array([1, 2, 3])

In [6]:
#Create array matrix
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
array_mat = np.array(my_mat)
array_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#Create numpy array is a rapid and useful form
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [16]:
#Identity matrix --> are quare matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
#Generates an array with random sample from a uniform distribution over 0 to 1
np.random.rand(5)

array([0.22526961, 0.28036174, 0.87961689, 0.26183292, 0.52811685])

In [18]:
np.random.rand(5,5)

array([[0.80522371, 0.51100638, 0.76894668, 0.95914267, 0.58245655],
       [0.48240871, 0.59378437, 0.56024281, 0.7352693 , 0.72229669],
       [0.03254406, 0.36887266, 0.02554566, 0.32285272, 0.48819595],
       [0.85305378, 0.33245824, 0.76427743, 0.89747626, 0.59343403],
       [0.85466462, 0.89559592, 0.85053573, 0.987081  , 0.73017749]])

In [19]:
#Generates random samples from the standard normal distribution or a Gaussian distribution -> centered around 0
np.random.randn(2)

array([0.76088788, 0.38231368])

In [20]:
np.random.randn(4,4)

array([[ 0.01591149, -0.37147187,  1.10634043, -1.27196026],
       [ 0.49622243,  2.45558945, -0.79426718,  1.5101803 ],
       [ 3.04649115, -0.99534926, -0.17414251, -0.77165819],
       [-1.45957925,  1.41451493, -1.28946447,  0.38506698]])

In [21]:
#Generates a random integer number from a low to a high number. Low inclusive and high is exclusivve
np.random.randint(1,100)

43

In [22]:
np.random.randint(1,100,10)

array([45, 18, 40,  8, 44, 15, 35, 61, 40, 88])

#### Numpy Array Operations

In [24]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr = np.random.randint(0,50,10)
ranarr

array([18, 26, 16, 46, 42, 18, 21,  4,  3, 27])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
arr.reshape(5,10) #The number of rows * number of colums must be igual to the total of elemets on the array

ValueError: cannot reshape array of size 25 into shape (5,10)

In [29]:
ranarr

array([18, 26, 16, 46, 42, 18, 21,  4,  3, 27])

In [30]:
ranarr.max()

46

In [31]:
ranarr.min()

3

In [33]:
index_max = ranarr.argmax()
index_max

3

In [34]:
index_min = ranarr.argmin()
index_min

8

In [36]:
arr.shape

(25,)

In [38]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr.shape

(5, 5)

In [41]:
arr.dtype

dtype('int64')

#### Numpy Array Indexing and Selection

In [46]:
#Indexing and Selection 1d array
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[8]

8

In [48]:
arr[1:5]

array([1, 2, 3, 4])

In [49]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [50]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [51]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [53]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [55]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
slice_of_arr= arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [57]:
slice_of_arr[:] = 99 #--> the change will occur on the original array
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [58]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [59]:
#Is necessary to copy teh array before change it
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
arr_copy[:] = 100 #--> original array will not change, only the arr_copy
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [61]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
#Indexing and Selection 2d array

In [63]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
arr_2d[0][0] #--> element in row 0 and column 0

5

In [65]:
arr_2d[0] # --> row 0

array([ 5, 10, 15])

In [66]:
arr_2d[2,1]

40

In [67]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [69]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [ ]:
#Conditional Selection

In [70]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
bool_array = arr > 5

In [73]:
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [74]:
arr[bool_array] #--> return elements that the result conditional was True

array([ 6,  7,  8,  9, 10])

In [75]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [76]:
arr[arr<3]

array([1, 2])

#### Numpy Operations

- Array with Array
- Array with Scalars
- Universal Array Functions

In [78]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr + arr #sum each element on arr1 with each element of array 2 --> respetion the element position

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [83]:
arr - arr 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [80]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [81]:
arr + 100 # --> sum 100 to each element of the array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [82]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [84]:
arr / arr

<ipython-input-84-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [85]:
1/arr

<ipython-input-85-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [86]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [87]:
#Universal Array Functions

In [88]:
np.sqrt(arr) #--> calculate the sqyare root all of each element of teh array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [89]:
np.exp(arr) # --> calculate sthe exponencial of each element of the array

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [90]:
np.max(arr) # --> same as arr.max()

10

In [91]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [92]:
np.log(arr)

<ipython-input-92-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])